### PR TITLE
Add support for `visionOS`

### PR DESCRIPTION
**Pull request by NachoSoto**

### CODE REVIEW

**Review by joshdholtz — APPROVED** [review]

**Comment by bielikb** [comment]
Thanks for the contribution!

**Comment by bielikb** [comment]
FYI, I'm going to provide a few more changes before kicking off the new release of this plugin.

**Comment by NachoSoto** [comment]
Something seems wrong with the implementation now. I can't get it to finish past this error:
> [!] ▸ PRODUCT_NAME was misdefined: `RevenueCat`. Please, provide :product_name option

That's with this call:
```ruby
create_xcframework(
  destinations: [
        'iOS',
        'macOS',
        'maccatalyst',
        'tvOS',
        'watchOS',
        'visionOS'
   ],
  scheme: 'RevenueCat',
  product_name: 'RevenueCat',
  xcframework_output_directory: output_directory,
  # Bitcode is no longer required since Xcode 14.
  enable_bitcode: false,
  include_debug_symbols: true
)
```

**Comment by NachoSoto** [comment]
Have you verified that this plugin works with Xcode 15?

**Comment by NachoSoto** [comment]
Oh never mind, I needed `override_xcargs: true`

**Pull request merged**
